#!/usr/bin/env python3
"""
generate_eu_tables.py — Generate eu_tables.h for Gadget-4 EU simulation

Generates C++ header with hardcoded arrays for:
  1. f_cdm(z) — CDM drain fraction (analytical, NB01 formula)
  2. E(z) = H_EU(z)/H0 — Dimensionless Hubble parameter (modified Friedmann)

Usage:
  python generate_eu_tables.py [--n-points 10000] [--normalize-H0]

Output:
  eu_tables.h — C++ header file with static arrays and interpolation functions

Author: EU Pipeline (NB10)
Date: 2026-05-31
"""

import numpy as np
import argparse
import sys

# ============================================================
# EU Cosmological Parameters (MCMC C2 best-fit, Δk=0)
# ============================================================

# Standard cosmology (primordial values)
H0       = 68.886      # km/s/Mpc
h        = H0 / 100.0  # 0.68886
omega_b  = 0.02237     # ω_b (primordial, conserved)
omega_cdm= 0.1193      # ω_cdm (PRIMORDIAL — see WARNING in NB10 v5)
n_s      = 0.9649
A_s      = 2.1e-9
tau_reio = 0.0544

# Derived Ω parameters
Omega_b       = omega_b / h**2        # ~0.04714
Omega_cdm_prim= omega_cdm / h**2      # ~0.25142
Omega_m_prim  = Omega_b + Omega_cdm_prim  # ~0.29856

# Radiation (CMB photons + 3 massless neutrinos, Planck 2018)
T_CMB = 2.7255  # K
Omega_gamma = 2.469e-5 / h**2   # photons
N_eff = 3.046
Omega_nu = N_eff * (7.0/8.0) * (4.0/11.0)**(4.0/3.0) * Omega_gamma
Omega_r = Omega_gamma + Omega_nu  # total radiation

# EU drain parameters (NB01 UV derivation, Δk=0, fixed in C2)
# Source: analysis_RUN_C2.md line 15
epsilon_IR = 0.04264        # 1/√(108π) — drain intensity
z_trans    = 5.986          # CKN spherical threshold
b_param    = 19.0 / 36.0    # = 0.52778 — sigmoid steepness


# ============================================================
# 1. f_cdm(z) — Analytical drain function (NB01)
# ============================================================

def sigmoid_s(z):
    """Sigmoid activation function s(z) from NB01 §3.
    s(z) = 1 / (1 + ((1+z)/(1+z_trans))^(1/b))
    s(0) = s0, s(z_trans) = 0.5, s(z→∞) → 0
    """
    ratio = (1.0 + z) / (1.0 + z_trans)
    return 1.0 / (1.0 + ratio**(1.0 / b_param))

# Compute s(0) for normalization
_s0 = sigmoid_s(0.0)

# CLASS-EU exact value from C2 analysis
_fcdm_z0_exact = 0.955765  # from analysis_RUN_C2.md line 96

# Calibrate: epsilon_eff such that f_cdm(0) = 1 - epsilon_eff * s(0) = 0.955765
# => epsilon_eff = (1 - 0.955765) / s(0)
_epsilon_eff = (1.0 - _fcdm_z0_exact) / _s0

def f_cdm(z):
    """CDM drain fraction: f_cdm(z) per NB01 Eq. 1.6b.
    
    Implements the HEAVISIDE CUTOFF at z_trans:
      f_cdm(z) = 1.0                          for z > z_trans
      f_cdm(z) = 1 - ε_eff × s(z)             for z ≤ z_trans
    
    The ghost condensate nucleates as a quantum phase transition
    at z_trans. The order parameter is STRICTLY ZERO for z > z_trans
    (NB01 §1.4.1, §5.6.1). There is no exponential tail.
    
    Calibrated so that f_cdm(0) = 0.955765 (CLASS-EU C2 exact).
    """
    if z > z_trans:
        return 1.0  # NB01 Eq. 1.6b: ε(z) = 0 for z > z_trans
    return 1.0 - _epsilon_eff * sigmoid_s(z)





# ============================================================
# 2. H_EU(z)/H0 — Modified Friedmann equation
# ============================================================

def compute_hubble_eu(z_array):
    """Compute E(z) = H_EU(z)/H0 from modified Friedmann equation.
    
    Uses flat-universe Friedmann with f_cdm(z)-modified CDM density.
    Lambda_eff set by z=0 normalization: E(0) = 1.0 exactly.
    
    Error from constant-Lambda approximation: < 0.1% for 4.4% drain.
    """
    Omega_Lambda_0 = 1.0 - Omega_r - Omega_b - Omega_cdm_prim * f_cdm(0.0)
    
    E_array = np.zeros(len(z_array))
    for i, z in enumerate(z_array):
        opz = 1.0 + z
        E2 = (Omega_r * opz**4
              + Omega_b * opz**3
              + Omega_cdm_prim * f_cdm(z) * opz**3
              + Omega_Lambda_0)
        E_array[i] = np.sqrt(max(E2, 0.0))
    
    return E_array


# ============================================================
# 3. Generate C++ header
# ============================================================

def generate_header(z_array, fcdm_array, E_array, filename="eu_tables.h"):
    """Write eu_tables.h with hardcoded arrays and interpolation functions."""
    
    n = len(z_array)
    
    with open(filename, 'w') as f:
        f.write("// eu_tables.h — Auto-generated by generate_eu_tables.py\n")
        f.write("// EU Cosmological tables for Gadget-4 N-body simulation\n")
        f.write(f"// Generated with {n} points, z = [{z_array[0]:.2f}, {z_array[-1]:.2f}]\n")
        f.write(f"// Parameters: eps_IR={epsilon_IR}, z_trans={z_trans}, b={b_param}\n")
        f.write(f"// H0={H0}, omega_b={omega_b}, omega_cdm={omega_cdm} (primordial)\n")
        f.write(f"// f_cdm(z=0) = {f_cdm(0.0):.6f}\n")
        f.write(f"// E(z=0) = {E_array[np.argmin(np.abs(z_array))]:.6f} (should be ~1.0)\n")
        f.write("//\n")
        f.write("// WARNING: omega_cdm = 0.1193 IS the primordial value.\n")
        f.write("// DO NOT divide by f_cdm(0) — see NB10 v5 WARNING.\n")
        f.write("//\n")
        f.write("// DT audit trail: round 1-5 corrections applied.\n")
        f.write("#ifndef EU_TABLES_H\n")
        f.write("#define EU_TABLES_H\n\n")
        
        f.write(f"static const int EU_TABLE_SIZE = {n};\n")
        f.write(f"static const double EU_Z_MIN = {z_array[0]:.10f};\n")
        f.write(f"static const double EU_Z_MAX = {z_array[-1]:.10f};\n\n")
        
        # z array
        f.write(f"static const double eu_z_table[{n}] = {{\n")
        for i in range(0, n, 8):
            chunk = z_array[i:i+8]
            f.write("    " + ", ".join(f"{v:.10f}" for v in chunk))
            if i + 8 < n:
                f.write(",\n")
            else:
                f.write("\n")
        f.write("};\n\n")
        
        # f_cdm array
        f.write(f"static const double eu_fcdm_table[{n}] = {{\n")
        for i in range(0, n, 8):
            chunk = fcdm_array[i:i+8]
            f.write("    " + ", ".join(f"{v:.10f}" for v in chunk))
            if i + 8 < n:
                f.write(",\n")
            else:
                f.write("\n")
        f.write("};\n\n")
        
        # E(z) = H(z)/H0 array
        f.write(f"static const double eu_hubble_table[{n}] = {{\n")
        for i in range(0, n, 8):
            chunk = E_array[i:i+8]
            f.write("    " + ", ".join(f"{v:.10f}" for v in chunk))
            if i + 8 < n:
                f.write(",\n")
            else:
                f.write("\n")
        f.write("};\n\n")
        
        # Interpolation functions
        f.write("""
// Linear interpolation helper
static inline double eu_interp(const double* table, double z) {
    // Guard: clamp z to valid range (DT round 4)
    if (z < EU_Z_MIN) z = EU_Z_MIN;
    if (z > EU_Z_MAX) z = EU_Z_MAX;
    
    // Find index
    double frac = (z - EU_Z_MIN) / (EU_Z_MAX - EU_Z_MIN) * (EU_TABLE_SIZE - 1);
    int idx = (int)frac;
    if (idx >= EU_TABLE_SIZE - 1) idx = EU_TABLE_SIZE - 2;
    double t = frac - idx;
    
    return table[idx] * (1.0 - t) + table[idx + 1] * t;
}

// f_cdm(z) — CDM drain fraction
static inline double interpolate_fcdm(double z) {
    return eu_interp(eu_fcdm_table, z);
}

// E(z) = H(z)/H0 — Dimensionless Hubble parameter
// IMPORTANT: Returns E(z), NOT H(z) in km/s/Mpc! E(z=0) = 1.0
static inline double interpolate_hubble_eu(double z) {
    return eu_interp(eu_hubble_table, z);
}

""")
        f.write("#endif // EU_TABLES_H\n")
    
    print(f"Generated {filename} with {n} points")
    print(f"  z range: [{z_array[0]:.2f}, {z_array[-1]:.2f}]")
    print(f"  f_cdm(z=0) = {fcdm_array[np.argmin(np.abs(z_array))]:.6f}")
    print(f"  E(z=0) = {E_array[np.argmin(np.abs(z_array))]:.6f}")
    print(f"  f_cdm(z=49) = {fcdm_array[-1]:.6f}")
    print(f"  E(z=49) = {E_array[-1]:.6f}")


# ============================================================
# 4. Validation
# ============================================================

def validate():
    """Run sanity checks on EU tables."""
    print("\n=== Validation ===")
    
    # f_cdm checks
    f0 = f_cdm(0.0)
    f_zt = f_cdm(z_trans)
    f_49 = f_cdm(49.0)
    f_7  = f_cdm(7.0)  # just above z_trans
    print(f"f_cdm(z=0)     = {f0:.6f}  (expected ~0.9558)")
    print(f"f_cdm(z_trans)  = {f_zt:.6f}  (expected ~{1 - epsilon_IR*0.5:.6f})")
    print(f"f_cdm(z=7)     = {f_7:.6f}  (expected 1.000000 — Heaviside)")
    print(f"f_cdm(z=49)    = {f_49:.6f}  (expected 1.000000 — Heaviside)")
    
    assert abs(f0 - 0.9558) < 0.001, f"f_cdm(0) = {f0}, expected ~0.9558"
    assert f_49 == 1.0, f"f_cdm(49) = {f_49}, expected EXACTLY 1.0 (Heaviside cutoff)"
    assert f_7 == 1.0, f"f_cdm(7) = {f_7}, expected EXACTLY 1.0 (z > z_trans)"
    
    # Omega checks
    Omega_Lambda_0 = 1.0 - Omega_r - Omega_b - Omega_cdm_prim * f0
    Omega_m_eff_0 = Omega_b + Omega_cdm_prim * f0
    print(f"\nOmega_b         = {Omega_b:.5f}")
    print(f"Omega_cdm_prim  = {Omega_cdm_prim:.5f}")
    print(f"Omega_m_eff(0)  = {Omega_m_eff_0:.5f}")
    print(f"Omega_Lambda(0) = {Omega_Lambda_0:.5f}")
    print(f"Omega_r         = {Omega_r:.6f}")
    print(f"Sum             = {Omega_r + Omega_m_eff_0 + Omega_Lambda_0:.6f} (should be 1.0)")
    
    # Omega_m for param_eu.txt
    Omega_m_param = Omega_b + Omega_cdm_prim  # primordial total
    print(f"\nOmega0 for param_eu.txt = {Omega_m_param:.5f}")
    
    print("\n[OK] All checks passed!")


# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Generate eu_tables.h for Gadget-4")
    parser.add_argument("--n-points", type=int, default=10000,
                        help="Number of table points (default: 10000)")
    parser.add_argument("--output", type=str, default="eu_tables.h",
                        help="Output filename (default: eu_tables.h)")
    parser.add_argument("--validate-only", action="store_true",
                        help="Only run validation, don't generate header")
    args = parser.parse_args()
    
    # Validate first
    validate()
    
    if args.validate_only:
        return
    
    # Generate z grid (ascending: 0 → z_max)
    z_max = 49.0
    z_array = np.linspace(0.0, z_max, args.n_points)
    
    # Compute f_cdm
    fcdm_array = np.array([f_cdm(z) for z in z_array])
    
    # Compute E(z) = H_EU(z)/H0
    print("\nComputing H_EU(z) from modified Friedmann equation...")
    E_array = compute_hubble_eu(z_array)
    
    # Sanity: E(z=0) should be ~1.0
    E0 = E_array[0]
    print(f"E(z=0) = {E0:.8f} (should be 1.000000)")
    assert abs(E0 - 1.0) < 0.01, f"E(0) = {E0}, expected ~1.0!"
    
    # Generate header
    generate_header(z_array, fcdm_array, E_array, args.output)
    print(f"\n[OK] {args.output} generated successfully!")


if __name__ == "__main__":
    main()
